### ISSUE TITLE
CSV describing Expected JSONLD results

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/GeoCODES-Metadata#10]
Link to #6

pass/fail
html/json
what search would retrieve the result
is there a tool linkage that would be expected
others

**Comment by MBcode** [comment]
Once we have more specific failure test-data as mentioned in [1](https://github.com/earthcube/geocodes_documentation/issues/1) we can go beyond 'ok'=there and blank, and present failure mode compared to expected failure mode

**Comment by valentinedwv** [comment]
Present testing uses acceptance testing approach.
