### ISSUE TITLE
ECRR-QA: sparql queries to test to see if things got loaded

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/GeoCODES-Metadata#4]
We need to be sure that items get pushed.

For a record or two here, and for a record or two of the ecrr_submitted form. can we get a sparql query

maybe just an ask query that we could template as a last step.

servers to test:
graph. geocodes. earthcube .org
graph. geodex . org
the fuskei triplestore

**Comment by MBcode** [comment]
this is handled by [this](https://github.com/MBcode/ec/blob/master/test/ingestTesting.md) notebook

**Comment by MBcode** [comment]
Issue[43](https://github.com/earthcube/ECOTechTeam/issues/43) handles this

incl. [get_graph_per_repo](https://github.com/MBcode/ec/blob/master/ec.py#L1635) will give the numbers to each repo, then you can compare w/each of their sitemap's
